[workspace]
resolver = "2"
members = [
    "demo",
    "macros"
]

[workspace.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

egui = "0.33"
eframe = {version = "0.33", default-features = false}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
